# Generated by Django 3.1.1 on 2020-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvendor', '0005_question_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('fillrate', models.CharField(max_length=4000)),
                ('instockprob', models.CharField(max_length=4000)),
                ('org', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mean', models.CharField(max_length=200)),
                ('standard', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=4000)),
            ],
        ),
    ]
