# Generated by Django 3.1.1 on 2020-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvendor', '0006_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('qid', models.PositiveIntegerField()),
                ('feedback', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
